### ISSUE TITLE
Group of reviewers per label

### ISSUE THREAD

**Issue by k-mitevski** [kentaro-m/auto-assign-action#111]
Hello 👋 
Not sure if this is a feature of this action, but is it possible to auto-assign reviewers based on a specific label?

Example, if the label `backend` is applied only reviewers from the backend group would be assigned to the PR. Same for the `frontend` label.
```
# Set to true to add reviewers from different groups to pull requests
useReviewGroups: true

# A list of reviewers, split into different groups, to be added to pull requests (GitHub user name)
reviewGroups:
  backend:
    - reviewerA
    - reviewerB
    - reviewerC
  frontend:
    - reviewerD
    - reviewerE
    - reviewerF
    - 
filterLabels:
  include:
    - backend
    - frontend
  # Not run
  exclude:
    - wip
```

Thank you.
