### ISSUE TITLE
Allow specification of number of people to select from each group

### ISSUE THREAD

**Issue by jjmaun** [kentaro-m/auto-assign-action#13]
I might be missing it, but if not, it would be cool if the configuration allowed for specification to the number of reviewers to be selected from each review group. For example

```
numberOfReviewersGroupA: 1

numberOfReviewersGroupB: 2

reviewGroups:
  groupA:
    - foo
    - bar
  groupB:
    - foobar
    - baz
    - foobaz
```

I understand this may be a bit challenging to pull off, but throwing it out there.
