### ISSUE TITLE
Warnning "Resource not accessible by integration" reported and no reviewers are assigned.

### ISSUE THREAD

**Issue by bluven** [kentaro-m/auto-assign-action#136]
I was trying out this action, but an warning "Resource not accessible by integration" was reported and no reviewers were assigned.

The  output  is here: https://github.com/bluven-org/test/actions/runs/5374670624/jobs/9750300069

My action config:

```
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: '.github/reviewers2.yaml' # Only needed if you use something other than .github/auto_assign.yml
```

**Comment by Secreto31126** [comment]
Try using this permissions, they worked for me:

```yml
permissions:
  contents: read
  pull-requests: write
```
