### ISSUE TITLE
If reviewers already assigned, skip

### ISSUE THREAD

**Issue by brianeclow** [kentaro-m/auto-assign-action#16]
We are finding it annoying when a PR requester takes care to request specific people to review a PR, then the action comes along and adds more. A great flag would be to be able to skip adding reviews if the `numberOfReviewers` has been met or to skip adding reviews completely in this case.

**Comment by vistaar-dgada** [comment]
@brianeclow //cc @kentaro-m  You're searching for action to run only once. Usually it runs on every push on PR. So i think this will take care of it. 

```
name: 'Auto Assign'
on:
  pull_request:
    types: [opened, reopened]
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

**Comment by brianeclow** [comment]
Nope!
@vistaar-dgada That is not what I'm asking for at all. I already have the action run only once upon opening of the PR. I am looking for the action to be _**skipped**_ if reviewers have already been set by someone when the PR _**was created**_. This means, the author has specific reviewers in mind, and adding new people confuses all involved.

If I am understanding correctly, the code can check the reviewer array, and act accordingly. And at that point, we could get options: no action taken, add reviewers from the pool to bring up to the desired total, add reviews from the pool, etc.
My ask is for at least `no action` and `add users from pool`.

**Comment by dsazup** [comment]
We are running into the same issue too. For example if I create a non-draft, normal PR it assigns 2 reviewers. Let's say I instantly mark that PR as draft. Now when I mark it ready for review again, it adds 2 more reviewers which is not really expected.

**Comment by PrinsFrank** [comment]
I just managed to work around it for now by adding a condition to the job like this:
<pre>
name: 'Auto Assign'
on:
  pull_request:
    types: [opened, reopened]
jobs:
  add-reviews:
    <b>if: github.event.pull_request.requested_reviewers.*.name == ''</b>
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
</pre>

**Comment by dsazup** [comment]
@PrinsFrank interesting, though doesn't seem to work for me. When I submit a PR, it just skips the action all together initially 🤔

**Comment by brianeclow** [comment]
@PrinsFrank That does not work. I did several iterations around it, and github actions will not let you test an empty array in that fashion or in any way I could think of. This is final configuration I ended up with before stopping:
```
name: 'Auto Assign'
on:
  pull_request:
    types: [opened, reopened]

jobs:
  triage-assign-and-review:
    if: contains(github.event.pull_request.requested_reviewers.*.login, '') && contains(github.event.pull_request.requested_teams.*.slug, '')
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

**Comment by kentaro-m** [comment]
Hi, @brianeclow! Thanks for waiting.

I thought a good idea which checking exist assignees or reviewers before adding its to PR.

1. Checking existed reviewers
    1. Skip the process to add reviewers if PR has reviewers
2. Adding reviewers if no reviewers
3. Checking existed assignees
    1. Skip the process to add assignees if PR has assignees
4. Adding assignees if no assignees

I think it's better to control the skipping process as the logic of the application rather than the if syntax of the workflow.

If you have any concerns, please let me know.

**Comment by carlisia** [comment]
> I thought a good idea which checking exist assignees or reviewers before adding its to PR.

This sounds good to me. To be clear, it should precisely be checking that the "number" of reviewers/assignees match what's specified in the config file.

I'm having the same general problem, but specifically one no one has mentioned: I open a PR, the right number of (random) reviewers get added. Any subsequent commit pushed to that PR will trigger more reviewers being assigned,

**Comment by idonov8** [comment]
My team encountered this problem. Is there any up-to-date solution?
@carlisia is the problem fixed on the GitHub App version? Should we switch to using it?

**Comment by carlisia** [comment]
Hey @idonov8 I haven't tested or used this action in a long while, sorry I cannot be of help.

**Comment by AlexanderKrogsgaard** [comment]
Any news on this?

The hack I resorted to was an additional step checking for number of already assigned reviewers, and then failing this step if there are already assigned reviewers. We also only need at least 1 reviewer, sooo 🤷 

```
- name: Check for reviewers
  run: |
    NUM_REVIEWERS=$(gh pr view --json reviewRequests | jq '.reviewRequests | length')

    if (( NUM_REVIEWERS > 0 )); then
      echo "Reviwer(s) already on it. No need to assign more."
      exit 1
    else
      exit 0
    fi
- name: Review lottery
  if: success()
```

**Comment by ClaudioConsolmagno** [comment]
This seems to work:
```
jobs:
  auto-assign-pr-to-author:
    if: ${{ github.event.pull_request.assignees == null || toJSON(github.event.pull_request.assignees) == '[]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
```
