### ISSUE TITLE
feature: Allow waiting for actual build

### ISSUE THREAD

**Issue by richtera** [kentaro-m/auto-assign-action#209]
Currently reviews are initiated when the PR is initially opened which is good, but not great. Ideally it should also consider the first build or status checks on the PR before sending requests for the code to be reviewed. I tried various things, but failed. It would be better if the action internally was able to check whether it already sent the review, then it could be inserted into the normal build flow after all status (lint, format, build and so) are successfully completed.
It could then also be configured to re-request reviews if the repo was setup to require new reviews on new pushes.
Or is there a way to do this I was not able to figure out?

**Comment by richtera** [comment]
I was playing with something like this which optionally executes the action. This can be inserted after the build/lint/verify steps so that only valid builds cause the notification. A user can also remove the label to cause a new notification later on (similar to draft non-draft switching)
```yaml
      - name: Get Pull Request Info
        id: pr-info
        if: ${{ github.event.number != null }}
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return pr.data.draft && !pr.data.labels.some(label => label.name === 'review-requested') ? "true" : "false";

      - name: Output info
        run: echo "${{ steps.pr-info.outputs }}"
      
      - name: Conditionally Run Auto-Assign
        if: ${{ github.event.number != null && steps.pr-info.outputs == true }}
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto_assign.yaml'

      - name: Add 'review-requested' Label
        if: ${{ github.event.number != null && steps.pr-info.outputs == true }}
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['review-requested']
            });
```
