### ISSUE TITLE
numberOfReviewers is misleading when useReviewGroups is enabled

### ISSUE THREAD

**Issue by paniko0** [kentaro-m/auto-assign-action#24]
Assuming the following configuration, I'd expect that only one reviewer would be selected given that `numberOfReviwers` is set to 1, instead, it returns 3 values: user1, user2, and a user in the charlie group.

```
addReviewers: true

numberOfReviewers: 1

useReviewGroups: true

reviewGroups:
  alpha:
    - user1
  bravo:
    - user2
  charlie:
    - user3
    - user4
    - user5
```

I believe either the name of the configuration `numberOfReviwers` is misleading when `useReviewGroups` is enabled, or there's a bug where it assigns more than one reviewer to the PR. 

I can work on a PR to fix the problem, I just need to know which approach you guys think it's the best. Personally, I think `numberOfReviewers` should always be respected regardless of the number of developers each group has. I'd also include a configuration to the group, so it can select one or multiple developers per group to be used later by the `numberOfReviewers` variable.
