### ISSUE TITLE
`[warning]Resource not accessible by integration` when running against PRs

### ISSUE THREAD

**Issue by nrb** [kentaro-m/auto-assign-action#29]
Given the following workflow:

```yaml
name: 'Auto Assign PR Reviewers'
on: pull_request

jobs: 
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.1
        with: 
          configuration-path: ".github/auto_assign.yml"
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
```

And the following `auto_assign.yml`:

```yaml

addReviewers: true
addAssignees: author

reviewers:
  - nrb
  - ashish-amarnath
  - carlisia
```

I see the following output when running this action against all PRs

```
Run kentaro-m/auto-assign-action@v1.1.1
  with:
    configuration-path: .github/auto_assign.yml
    repo-token: ***
##[warning]Resource not accessible by integration
##[warning]Resource not accessible by integration
```

I'm not quite sure what I've got wrong. You can see the directory structure at https://github.com/vmware-tanzu/velero/tree/main/.github

I was also seeing this behavior without the `GITHUB_TOKEN`, and added it thinking that would give the action access to act on the repository.
