### ISSUE TITLE
Explain the purpose of review groups

### ISSUE THREAD

**Issue by phcoliveira** [kentaro-m/auto-assign-action#50]
Gretings!

I did not understand why would anyone use groups with the current implementation. For example, assume that I am `devA`.

```
# Single list
reviewers:
  - devA
  - devB
  - devC
  - devD
```

```
# Multiple groups
useReviewGroups: true
reviewGroups:
  fe:
    - devA
    - devB
  be:
    - devC
    - devD
```

In both cases, all the other 3 devs will be assigned.

I expected that, because I belong to team `fe`, only `devB` would be assigned. Instead, the result is the same as of using a single list.
