### ISSUE TITLE
Does not add a reviewer

### ISSUE THREAD

**Issue by Power-Maverick** [kentaro-m/auto-assign-action#55]
I have the config as presented below. The action is adding the author but does not adds me as a reviewer.

```
addReviewers: true
addAssignees: author
reviewers:
  - Power-Maverick
numberOfReviewers: 0
```

**Comment by grandeljay** [comment]
I am getitng an error though. Is this still an issue or am I doing something wrong?

```log
The workflow is not valid. .github/workflows/auto-assign.yml (Line: 15, Col: 23): A sequence was not expected .github/workflows/auto-assign.yml (Line: 17, Col: 23): A sequence was not expected
```

```yml
name: "Auto Assign"
on:
    pull_request:
        types: [opened, ready_for_review]

jobs:
    add-reviews:
        runs-on: ubuntu-latest
        steps:
            - uses: kentaro-m/auto-assign-action@v1.2.4
              with:
                  addReviewers: true
                  addAssignees: author
                  reviewers:
                      - "grandeljay"
                  skipKeywords:
                      - wip

```
