### ISSUE TITLE
Allow assignment on pull_request_review action

### ISSUE THREAD

**Issue by samkio** [kentaro-m/auto-assign-action#68]
Hi we are trying to set up this action such that when a PR is approved by a developer this action will auto-assign a QA engineer. The following is my GitHub action and auto-assign-action config. When this is used however the message `Warning: Empty value for parameter 'pull_number': undefined` is shown. I believe this is because we are using the `pull_request_review` action instead of `pull_request` or `pull_request_target` and so the PR number cannot be found. Is there a way to do this today or is a change required to add this functionality?

.github/auto_assign_qa.yml
```yml
addReviewers: true
addAssignees: false

reviewers:
  - samkio

numberOfReviewers: 0
```

.github/workflows/qa-assign.yml
```yml
name: "Auto assign QA reviewers"
on:
  pull_request_review:
    types: [submitted]
jobs:
  add-qa-reviewers:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "ready for test"
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: ".github/auto_assign_qa.yml"
```

Log:
```
Run kentaro-m/auto-assign-action@v1.2.1
  with:
    configuration-path: .github/auto_assign_qa.yml
    repo-token: ***
Warning: Empty value for parameter 'pull_number': undefined
```
